### ISSUE TITLE
Issues running on Steam Deck

### ISSUE THREAD

**Issue by kaosjr** [Xpl0itU/WiiUDownloader#11]
Hi,
I've been having trouble running the appimage on the Steam Deck because of an incompatible glibc version. The deck currently ships with glibc 2.33, but the application seems to require 2.34, which is impossible to install with the default OS setup.

![image](https://user-images.githubusercontent.com/16449077/204069016-2033b393-d919-407a-ad56-cafe02ba50b6.png)
![image](https://user-images.githubusercontent.com/16449077/204069023-57a40169-7ed2-4238-8a47-cda90b68d5c6.png)

Is there any way you could compile with glibc 2.33 for Steam Deck support?

**Comment by Xpl0itU** [comment]
Thing is, I don’t have a steam deck, although I have arch linux in my main computer (steam deck OS is based in arch), I don’t suffer from that issue, so, uh, you’ll have to compile it from source if you want to use it

**Comment by Xpl0itU** [comment]
Could you try running this? [https://we.tl/t-2DLFvhmVb6](https://we.tl/t-2DLFvhmVb6)

**Comment by Xpl0itU** [comment]
If it doesn't work, try this [https://we.tl/t-grgopRHbRF](https://we.tl/t-grgopRHbRF)

**Comment by Xpl0itU** [comment]
Follow this:
```git clone --recursive https://github.com/Xpl0itU/WiiUDownloader
cd WiiUDownloader
makepkg -si
```

This should build WiiUDownloader, to run it simply type in a terminal `WiiUDownloader`

**Comment by kaosjr** [comment]
> Follow this:
> 
> ```
> git clone --recursive https://github.com/Xpl0itU/WiiUDownloader
> cd WiiUDownloader
> makepkg -si
> ```
> 
> This should build WiiUDownloader, to run it simply type in a terminal `WiiUDownloader` or run it from the apps menu

Tried this, got a new error:
![image](https://user-images.githubusercontent.com/16449077/204111113-0a9a28a3-4e68-41b8-877c-f2c49c0c225e.png)

Searching it up it seems to be because there's no fakeroot binary installed on the system by default. Pacman doesn't work on the default install though (since the OS is read-only), and I don't really want to disable the read-only mode because it causes issues when the system needs to update down the line. Not entirely sure what to do next.

**Comment by Xpl0itU** [comment]
You can always run this on another PC and use it there instead, but a binary should’ve been built in the build folder, so run that too

**Comment by kaosjr** [comment]
No luck, same error if you don't include arguments when running makepkg. I'll just have to use it on my desktop and transfer files over. Hopefully the next system update for the Deck includes a newer glibc version...
