### ISSUE TITLE
Request for stable compatibility mode for previous windows 8, windows 7, and vista at the very least

### ISSUE THREAD

**Issue by chronostrider23** [Xpl0itU/WiiUDownloader#113]
Just recently discovered WiiUDownloader and was really excited on unpacking it and start downloading wii u games since usb helper is now a mess nowadays . ONLY to be disappointed that no matter what i do. the latest release v2.60 for my old windows 7 won't ever launch even if  i configured it for compatibility for windows 7. another odd thing is the settings for the compatibility seems to be disabled. 
![WiiUDownloader exe](https://github.com/user-attachments/assets/6fccfab1-0a14-41f4-99cb-27e6e1a8c5eb)

i humbly request, that you please include a very stable compatibility mode for older windows, and other old OS that you supported in the next update  since the only stable compatibility are previous and current OS.  Nusplii download is good but very slow. The only option in downloading a faster wii u game is your wiiu downloader since usb helper library nowadays are mess. some games are all japanese although us and eur are in the label..   

Sorry for this lenghthy request.

**Comment by Xpl0itU** [comment]
Can’t, Go doesn’t support old windows versions

**Comment by chronostrider23** [comment]
> Can’t, Go doesn’t support old windows versions

That's to bad. What's the oldest and lowest windows that is compatible?
what windows versions does wiiu downloader support?

**Comment by Xpl0itU** [comment]
It should support W10 and upwards
