### ISSUE TITLE
Decrypt issue

### ISSUE THREAD

**Issue by powl999** [Xpl0itU/WiiUDownloader#13]
When I downloaded botw in a queue the dlc decrypts but the failed so now I have to download it again

**Comment by powl999** [comment]
I use arch btw

**Comment by Xpl0itU** [comment]
It happens, it’s a cdecrypt issue, you can use JNUSLibDecryptor instead with the already downloaded files

**Comment by powl999** [comment]
Cool thanks

**Comment by powl999** [comment]
Do you have an other idea I don't understand how the jnuslibdecryptor work

**Comment by Xpl0itU** [comment]
Alright, the issue is path lenght, try downloading botw to C:/Games, that folder isn’t probably there, so create it, after that, the decryption will succeed
