### ISSUE TITLE
AppImage not opening on linux

### ISSUE THREAD

**Issue by NomeJaExiste** [Xpl0itU/WiiUDownloader#14]
I'm using debian 11, I made the appimage executable but when I doubleclick nothing happens, and when I tried opening it from the terminal it spams 'GCLIB 2.33 is missing' 
![image](https://user-images.githubusercontent.com/92635630/209859966-1242e4a8-e92c-48bf-982e-e842ec2169e4.png)

**Comment by Xpl0itU** [comment]
You might need to install glibc, refer to google on how to do that
