### ISSUE TITLE
MacOS release broken - crash on startup

### ISSUE THREAD

**Issue by RobertoD91** [Xpl0itU/WiiUDownloader#20]
MacOS 13.1
xcode-select version 2396
gtk installed with brew:
- gtk+
- gtk+3
- gtk-mac-integration
- gtk4
- gtkmm
- gtkmm3
- gtkmm4

Mac releases from this github page:
v1.6-1.7 work
v1.8-1.13 crash on startup

self build with commit f04f802f87f2f10dbd3402f31b15606220d320c6
the binary in `build/WiiUDownloader` is ok
the bundle in `out/WiiUDownloader.app` give the error "segmentation fault: 11"

**Comment by Xpl0itU** [comment]
You can't have any gtk package installed when using the release, it's a weird restriction but it happens
