### ISSUE TITLE
Download speed inconsistency

### ISSUE THREAD

**Issue by ttuleyb** [Xpl0itU/WiiUDownloader#21]
Hello, I've been using this downloader on a fast network, however the download speeds seem a bit hit and miss. Sometimes the downloader starts off around 15-25MB/s and finishes the downloads very quickly, other times it starts at 2MB/s or even 200KB/s and hovers around that speed until I cancel and restart the download.

MacOS 13.1

Any knowledge of the cause of this?

**Comment by Xpl0itU** [comment]
I optimized WiiUDownloader to the best I could, might be either Nintendo’s servers or the fact that a lot of small files have to be downloaded, which makes speeds inconsistent, so I don’t think it’s a WiiUDownloader issue
