### ISSUE TITLE
Tagging/Flagging titles that are actually just Wii games

### ISSUE THREAD

**Issue by agilly1989** [Xpl0itU/WiiUDownloader#23]
Would it be possible (in the database or in the UI) to flag these titles https://en.wikipedia.org/wiki/List_of_Wii_games_on_Wii_U_eShop to say that they won't work on Cemu?

**Comment by ttuleyb** [comment]
I am sure you can get ChatGPT to convert that table into an array of games, you may need to link the games themselves to their titleID's or something identifiable by the WiiUDownloader though. After that, you can append it to their title name or something else.

**Comment by Xpl0itU** [comment]
A way would be to parse the FST to look for a file called fw.img, but I have no experience doing that

**Comment by ttuleyb** [comment]
You can just add a new row that says "Wii" and then tick it if name of the title matches any of the titles from the wikipedia. We could also just leave the user to do this for themselves, there are like 20 total games that are Wii and you can always use Dolphin

**Comment by Xpl0itU** [comment]
Implemented in master branch, will be out in next version
