### ISSUE TITLE
[Windows] Console windows appears on start

### ISSUE THREAD

**Issue by jessestricker** [Xpl0itU/WiiUDownloader#24]
On Windows, when I start the executable, an empty console windows appears and stays empty during the whole lifetime of the process.

Is this intended? 

Windows applications can be built as "GUI" applications that don't open a console window, see:
- [WinMain: The Application Entry Point, learn.microsoft.com](https://learn.microsoft.com/en-us/windows/win32/learnwin32/winmain--the-application-entry-point)
- [`add_executable`, cmake.org](https://cmake.org/cmake/help/latest/command/add_executable.html?highlight=win32)

If you like, I could open a PR for this.

**Comment by Xpl0itU** [comment]
Huh, I thought I removed it a while ago, try using the newest version

**Comment by AkechiiYEETS** [comment]
> On Windows, when I start the executable, an empty console windows appears and stays empty during the whole lifetime of the process.
> 
> Is this intended?
> 
> Windows applications can be built as "GUI" applications that don't open a console window, see:
> 
> * [WinMain: The Application Entry Point, learn.microsoft.com](https://learn.microsoft.com/en-us/windows/win32/learnwin32/winmain--the-application-entry-point)
> * [`add_executable`, cmake.org](https://cmake.org/cmake/help/latest/command/add_executable.html?highlight=win32)
> 
> If you like, I could open a PR for this.

I have the same issue.

> Huh, I thought I removed it a while ago, try using the newest version

I've downloaded the latest version but still encounter the issue

**Comment by Xpl0itU** [comment]
I just checked in a clean Windows 10 VM, it does NOT create a console window, it does appear for a brief moment when opening the program, you must've clicked on it, making it stay

**Comment by AkechiiYEETS** [comment]
Hey, i had my VPN enabled which somehow broke the program, disabling it made everything worth as normal.

**Comment by jessestricker** [comment]
I am quite certain that I didn't click on it. The documentation I've linked is the way to start an app without a console window, as recommended by Microsoft.
I do not use a VPN, so that can't be the issue here.

**Comment by jessestricker** [comment]
The issue was present on v1.13. I've just tried v1.14, it seems to be fixed now.

The commit that fixes this mentions Windows Terminal, and indeed I do use that over the default `conhost.exe` terminal, so maybe it was specific to that.
