### ISSUE TITLE
Encrypted files are not deleted after decryption

### ISSUE THREAD

**Issue by GlaZedBelmont** [Xpl0itU/WiiUDownloader#27]
Hi, I'm using the v1.14 appimage on a steam deck,

Noticed that the encrypted files never get deleted after being decrypted, leading to wasted storage. Is this by design or is this a bug?.

If so, is it possible to have a way to automatically delete them?

**Comment by Xpl0itU** [comment]
It’s made by design, but I can make a toggle for it too

**Comment by GlaZedBelmont** [comment]
That would be great, thanks!

**Comment by GlaZedBelmont** [comment]
https://github.com/Xpl0itU/WiiUDownloader/commit/cf442e755a395088b470514fe38b91b76ca3ce15

**Comment by ttuleyb** [comment]
Hello, I am on a mac and when this new checkbox is ticked on the latest version, it deletes the entire folder of the game after decryption, removing encrypted and decrypted contents.
