### ISSUE TITLE
[Request] Version numbers on release packages

### ISSUE THREAD

**Issue by parkerlreed** [Xpl0itU/WiiUDownloader#28]
If a script checks for an update via the file name, the current naming would lead to it never updating.

**Comment by Xpl0itU** [comment]
If you’re planning on making an updater, please do it in WiiUDownloader itself as it has an internal version (which just matches its version) instead of making a separate updater

**Comment by parkerlreed** [comment]
This was just for a basic personal update script on my system. Runs occasionally so I just told it to grab the download each time. 

Thanks.

**Comment by marvinlehmann** [comment]
Nevertheless it would be nice to see the version in a about dialog, window title or in the file properties on Windows at least:

![image](https://user-images.githubusercontent.com/4151266/230148694-9a996975-cddb-430b-87d3-4fe31db05d35.png)

But it seems to be hassle to me. I never liked .rc files, cmake etc though. x)
