### ISSUE TITLE
Delete Encrypted files deletes everything

### ISSUE THREAD

**Issue by ttuleyb** [Xpl0itU/WiiUDownloader#30]
Hello, I am on a mac and when this new checkbox is ticked on the latest version, it deletes the entire folder of the game after decryption, removing encrypted and decrypted contents.

Related issue:
https://github.com/Xpl0itU/WiiUDownloader/issues/27#issuecomment-1411080993_

**Comment by ttuleyb** [comment]
Please see: https://github.com/Xpl0itU/WiiUDownloader/pull/31

**Comment by Xpl0itU** [comment]
Merged
