### ISSUE TITLE
Decryption Issues

### ISSUE THREAD

**Issue by atlas1337** [Xpl0itU/WiiUDownloader#39]
OS: Win 11
Tool version: 1.18
Log file contains no data

Smash Bros fails to decrypt throwing the decryption error. Files are located at C:/Roms so file length shouldn't be an issue.

Update: Seems to happen with BOTW as well

Further Update: On 1.16 the core smash game downloaded and was decrypted, but the update failed to decrypt. The core BOTW decrypts but the update fails

**Comment by Xpl0itU** [comment]
Last time I touched anything regarding decryption and/or ticket generation was in 1.14, so, could you try using 1.13 and see if it happens there?

**Comment by atlas1337** [comment]
Neither decrypts with 1.13, but I got a log this time and have attached it
[log.txt](https://github.com/Xpl0itU/WiiUDownloader/files/10692847/log.txt)

**Comment by Xpl0itU** [comment]
Download got corrupted while downloading
