### ISSUE TITLE
MacOS not working

### ISSUE THREAD

**Issue by KapDEK** [Xpl0itU/WiiUDownloader#4]
It downloads a terminal file and when opened it does nothing. Here is what termanal says
<img width="567" alt="Screenshot 2022-11-12 at 11 41 15 AM" src="https://user-images.githubusercontent.com/83958311/201484760-e1eb6e1d-07e4-4184-a22c-6ab96dcf52a3.png">

**Comment by Xpl0itU** [comment]
I’m aware of it and I’ve been working on it the whole day, give me some time please

**Comment by Xpl0itU** [comment]
Could you redownload the latest release and test if It works?
