### ISSUE TITLE
[Windows] Entire app crashes/closes when trying to open the settings window

### ISSUE THREAD

**Issue by QuinTeknoLife** [Xpl0itU/WiiUDownloader#42]
I just downloaded the latest win version of this program, and I have noticecd that I cannot open the settings window. Whenever I try to, I first get a white MessageBox, followed by the entire program shutting down. Apparently this also results in a 0B completely empty log file.

I'll try the linux version on my dualboot later, and (if it does not slip my mind) try the windows version on one of my other machines to see if it makes any difference at all.

**EDIT:** Okay, I have figured out what was causing this issue. Apparently this happens when you try to open the settings pane without having a folder set as download location (which the progrram prompts us to do the first time we try to download something). Once the download folder is set the settings pane opens without a hitch.

**Comment by QuinTeknoLife** [comment]
I have figured out what was going on, see the edit in OP.

**Comment by Xpl0itU** [comment]
Does the issue happen on linux too or only on windows?

**Comment by QuinTeknoLife** [comment]
> Does the issue happen on linux too or only on windows?

Version 1.19 also had this behaviour on Linux, yes. I vertified that in 1.20 it is fixed (on both windows and Linux)
