### ISSUE TITLE
Meta.xml file missing

### ISSUE THREAD

**Issue by REZHub396** [Xpl0itU/WiiUDownloader#46]
When downloading and decrypting a game (I used Nintendo Land as a test), the meta.xml file is missing, so it's not usable in Cemu. Is this intentional or did I do something wrong?

**Comment by Xpl0itU** [comment]
Could you send me the download folder please? With all the .app and .h3 files, upload it to a mega or something

**Comment by REZHub396** [comment]
It worked. Thanks!
