### ISSUE TITLE
M1 mac issue with homebrew path to libraries

### ISSUE THREAD

**Issue by lenuisible** [Xpl0itU/WiiUDownloader#6]
Hi there,

I tried to install WiiUDownloader on my MBP M1, but got the following error:

Library not loaded: '/usr/local/opt/gtkmm3/lib/libgtkmm-3.0.1.dylib'
Referenced from: '/private/var/folders/*/WiiUDownloader.app/Contents/MacOS/WiiUDownloader'
Reason: tried: '/usr/local/opt/gtkmm3/lib/libgtkmm-3.0.1.dylib' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

It looks like homebrew doesn't use this path on M1 (see https://earthly.dev/blog/homebrew-on-m1/), would it be possible to propose a M1 dedicated download with the right path to packages please (/opt/homebrew/bin) ?

Thanks in advance,

Best Regards

**Comment by Xpl0itU** [comment]
Could you join the discord server (link in the gbatemp post) and we’ll try together to build an M1 version

**Comment by lenuisible** [comment]
Yep, just joined
