### ISSUE TITLE
[AppImage-Linux] Where's the cache located?

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [Xpl0itU/WiiUDownloader#62]
Hi. 
[Using the AppImage on Arch Linux]
I was downloading Injustice and it was dog slow (couple of hundred bits per second on a 100Mbps connection), so I pressed cancel. This did not work, it was stuck downloading for several minutes. After which, I killed the app. Now everytime I open the app, it is stuck in the 'Injustice' search screen and is unresponsive. I deleted the appimage and downloaded it again. But, it still goes back to the same screen every time I launch it.
I'm guessing this has to do with the app's cache, which I cannot find in `~/.cache.`. Where it located?

Thanks.

**Comment by Xpl0itU** [comment]
The app has no cache, reboot your computer
