### ISSUE TITLE
Closes on open and reopens an unusable window on Linux

### ISSUE THREAD

**Issue by MilkMan1093** [Xpl0itU/WiiUDownloader#66]
I just reopened the downloader to download a certain game, and the window closed to open again to a greyed out, unusable window. Where is the config directory of the app? I would like to see what the problem is.
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/88229702/c87db64c-fb09-49f8-9400-19b195b86e67)

**Comment by Xpl0itU** [comment]
Should be fixed with v2.0
