### ISSUE TITLE
Content that doesnt decrypt at all

### ISSUE THREAD

**Issue by Alecerzea** [Xpl0itU/WiiUDownloader#67]
Fatal Frame Maiden Black Water eshop Game and DLC (these one is detected by cemu even though there are some meta files not decrypted by the tool and causes a crash in the game selection mode)
Tekken Tag 2 Update
Twilight Princess Update
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/85199063/99ff7adc-dabb-48d3-ab75-5415a0261ddb)
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/85199063/a13dae5a-c8dc-4a2b-8fab-bb3e4ce4e241)
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/85199063/b4ed550f-ef75-417c-af21-11ac528febf8)
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/85199063/c87c6001-bed8-4670-879b-3380d975494a)

**Comment by Alecerzea** [comment]
It also happens in
Child of Light [0005000E1015B200] (Wii U Download Only) (TITLE v0010) (UPDATE v16)
China Warrior [0005000010165500] (TurboGrafx16)
Darts Up [0005000010135100] (Wii U Download Only) (TITLE v0000)
Devil's Third [0005000E10177600] (Wii U Retail & Download) (TITLE v0010) (UPDATE v16)
Mario & Sonic at the Rio 2016 Olympic Games [0005000E101E5300] (Wii U Retail & Download) (TITLE v0010) (UPDATE v16)
Mario Party 10 [0005000E10162D00] (Wii U Retail & Download) (TITLE v0010) (UPDATE v16)
Shockman [0005000010165D00] (TurboGrafx16)
Star Fox Guard [0005000E101BEC00] (Wii U Retail & Download) (TITLE v0010) (UPDATE v16)
Tokyo Mirage Sessions #FE [0005000E101ED800] (Wii U Retail & Download) (TITLE v0010) (UPDATE v16)
Wii Karaoke U [000500001010B800] (TITLE v0001)
Zumba Fitness World Party [0005000E10142A00] (Wii U Retail & Download) (TITLE v0010) (UPDATE v16)

**Comment by Xpl0itU** [comment]
Should be fixed with v2.0

**Comment by Alecerzea** [comment]
It doesnt 
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/85199063/3df4a59e-8461-4649-be98-b33ea466d64f)
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/85199063/9999bebd-634d-4e42-8663-76784e51254e)

**Comment by frenesus** [comment]
I have this issue on zelda twilight update too

**Comment by Alecerzea** [comment]
It's not needed to decrypt them nowadays, Cemu now has support for NUS format and games can launched that way and converted to .wua
