### ISSUE TITLE
crashes when i open settings

### ISSUE THREAD

**Issue by Wolfie-700** [Xpl0itU/WiiUDownloader#71]
it crashes when i open settings

https://github.com/Xpl0itU/WiiUDownloader/assets/79231568/2157b7f4-8adc-4037-b553-29514e7a1feb

**Comment by Wolfie-700** [comment]
> You’re using a very outdated version, get the latest one please

I got 2.16v and heres a screenshot, if it is outdated could you send me the lastest one please?
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/79231568/1e99f704-0e78-4a0a-a325-775830cb6958)

**Comment by Xpl0itU** [comment]
It is outdated, latest (v2.16) doesn’t even have a settings menu at all, remove everything related to WiiUDownloader and download again

**Comment by Wolfie-700** [comment]
The latest version I see is 2.16 and it says you updated it yesterday to version 2.16 could you add a link to the newest version, thanks.

**Comment by Xpl0itU** [comment]
latest is 2.16, you have downloaded an old version for some reason
