### ISSUE TITLE
[Bug] The progress window is still freezes in the latest appimage

### ISSUE THREAD

**Issue by ikaikahub** [Xpl0itU/WiiUDownloader#72]
I see the latest change log says this issue is fixed but I'm seeing this issue on the latest appimage. While downloading a queue of a couple games the dialog is frozen at Decrypting with the progress bar full. The queue finished downloading without any other issues

System info:
Operating System: Arch Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.7-zen1-3-zen (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-6700K CPU @ 4.00GHz
Memory: 31.3 GiB of RAM
Graphics Processor: llvmpipe
^ usually this says rtx 2070 ¯\\_(ツ)\_/¯
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: H170M-DS3H

**Comment by Xpl0itU** [comment]
Could you try with v2.17?

**Comment by Xpl0itU** [comment]
Could you try v2.17?

**Comment by k0b4lt** [comment]
I had a similar issue. when downloading, the current version was getting stuck on the last file and not moving to the Decrypting step.. Reverted to the 2.17 appimage and I can download and decrypt as expected
