### ISSUE TITLE
Write error after 5 attempts: 1

### ISSUE THREAD

**Issue by peepeevs** [Xpl0itU/WiiUDownloader#83]
Have been trying to solve this issue with someone on the Discord, and we couldn't figure it out. When I try to download any game to any drive (SSD and other) I get a new blank pop-up window, and after a long while I get a new pop-up with the message written in the title. 
Use Windows 10, have tried making exceptions with firewall, as well as fully disabling it. Have tried running as Admin. Nothing seems to work. Hope somebody knows what to do.

![Errror](https://github.com/Xpl0itU/WiiUDownloader/assets/160228426/de09271b-a66e-4806-8b49-f179a9b79da3)

**Comment by Xpl0itU** [comment]
Probably fixed with v2.50 and later https://github.com/Xpl0itU/WiiUDownloader/releases/latest
