### ISSUE TITLE
Very low download speed

### ISSUE THREAD

**Issue by Rex000** [Xpl0itU/WiiUDownloader#84]
I'm getting only around 200KB/s download speed

**Comment by sibwaze** [comment]
I've got the same issue bot speeds are up to 2 mbits/sec
is there any way to improve it?

**Comment by Xpl0itU** [comment]
Could you try updating WiiUDownloader to the latest version?

**Comment by Xpl0itU** [comment]
Fixed with v2.50 and later https://github.com/Xpl0itU/WiiUDownloader/releases/latest
