### ISSUE TITLE
[Enhancement] Do not overwrite ticket file if it exists. Allows legit owned tickets for download.

### ISSUE THREAD

**Issue by krisutofu** [Xpl0itU/WiiUDownloader#86]
I would like to backup my purchased digital games by redownloading them to an unencrypted accessible partition (without installing them).

I should be able to get at the tickets of my games using tik2sd. (And I possibly need to split them before using them.)

Would it be a good idea to allow selecting an owned ticket file instead of creating a fake ticket? It should work, right? Since the title ID and the title Key don't depend on the ticket.

Implementation is very easy I think, when the ticket file already exists in its place and no fake ticket needs to be written in [func GenerateTicket](https://github.com/Xpl0itU/WiiUDownloader/blob/60ecc29424adfa310fafcfac4268036626c85641/ticket.go#L9), i.e. returning early if the file exists already.

**Comment by Xpl0itU** [comment]
Simply download the whole game and overwrite the ticket after the download is done, WiiUDownloader creates a new directory for each game, so you can’t really add the ticket before WiiUDownloader gets the chance to overwrite it
