### ISSUE TITLE
Error when downloading large games

### ISSUE THREAD

**Issue by AltarOfMyEgo** [Xpl0itU/WiiUDownloader#90]
Getting this error when downloading large games (v2.46) :

context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by Xpl0itU** [comment]
v2.49 doesn’t exist, try this one https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.46

**Comment by AltarOfMyEgo** [comment]
My bad. I meant v2.46 😬

**Comment by Xpl0itU** [comment]
Try v2.29

**Comment by Xpl0itU** [comment]
Could you also try v2.47? it's currently building, so check in max 20 minutes from now on https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.47

**Comment by buttonmash147** [comment]
> Could you also try v2.47? it's currently building, so check in max 20 minutes from now on https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.47

Still not working for me.

**Comment by AltarOfMyEgo** [comment]
> Could you also try v2.47? it's currently building, so check in max 20 minutes from now on https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.47

Same issue with v2.47 : "context deadline exceeded (Client.Timeout or context cancellation while reading body)"

**Comment by Xpl0itU** [comment]
Again, same thing, in 20 minutes check this version https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.48

**Comment by buttonmash147** [comment]
Ok thanks

**Comment by buttonmash147** [comment]
Nope. Also, at some point, the counter telling you how many MBs have been downloaded regresses. (E. G. from 120 MB to 93)

**Comment by Xpl0itU** [comment]
Fixed with v2.50 and later https://github.com/Xpl0itU/WiiUDownloader/releases/latest
