### ISSUE TITLE
Error when downloading certain categories

### ISSUE THREAD

**Issue by MInecrafterPictures** [Xpl0itU/WiiUDownloader#91]
For Unknown, various system files and Wii other non-game/dlc files it gives me an error trying to download them

**Comment by MInecrafterPictures** [comment]
The games/dlcs download just fine thought, they're just System App, System Applet, Unknown, vWii System App and vWii System categories that I have issues with. They're just stuck at 0% and eventually give me a 404 download error after 5 attempts

**Comment by Xpl0itU** [comment]
What version are you using? If you don’t know or not sure, redownload WiiUDownloader and getting the latest version https://github.com/Xpl0itU/WiiUDownloader/releases/latest

**Comment by MInecrafterPictures** [comment]
I'm using the latest version. I attempted to download from System App, System Applet, Unknown, vWii System App and vWii System categories with only 404 errors as the result

**Comment by MInecrafterPictures** [comment]
Somehow even updates work

**Comment by Xpl0itU** [comment]
It was an error in the title database, should be fixed with v2.51
