### ISSUE TITLE
Decrypting error: "content not found"

### ISSUE THREAD

**Issue by bhartshorn** [Xpl0itU/WiiUDownloader#94]
Hi there, thanks for a great software.

I'm unable to decrypt downloaded content, I get only a small dialog box stating "content not found". This happens whether I check the "Decrypt contents" box or run the decrypt from the tools menu.
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/56871/f446c91a-8742-48a8-addb-184df4168547)

Running an updated Arch Linux and the latest AppImage. No relevant output when running from the terminal. Let me know any way I can help.

**Comment by bhartshorn** [comment]
Doing a little more troubleshooting, but I'm thinking it has something to do with the files being saved on an NTFS volume. WiiUDownloader seemingly has no problem writing to that drive, just decrypting.

**Comment by Xpl0itU** [comment]
What game and region?

**Comment by bhartshorn** [comment]
> What game and region?

Same error with Pikmin 1, 2, and 3, all US releases.

Thanks for quick response!

**Comment by bhartshorn** [comment]
Turns out to be related to the capitlization of the downloaded files. I added a debug to the error message which just prints the file it's unable to find, it's looking for lowercase but the files are uppercase.

![image](https://github.com/Xpl0itU/WiiUDownloader/assets/56871/4037490c-93ee-4a47-a4b8-51888d6392fd)

**Comment by Xpl0itU** [comment]
Fixed with v2.53
