### ISSUE TITLE
Decryption Error: Too many open files

### ISSUE THREAD

**Issue by wannafedor4** [Xpl0itU/WiiUDownloader#95]
While trying to download "The legend of Zelda: Breath of the Wild" DLC, I get this error:
![Screenshot 2024-04-20 at 2 20 37 PM](https://github.com/Xpl0itU/WiiUDownloader/assets/151413500/7ef4e35f-1f5a-4acd-882a-3c9c65d9fcb1)
- OS: macOS Sonoma 14.4.1 (23E224)
- CPU: Apple M2
- Memory: 8GB

Is this maybe a problem of having too many files in RAM at once?
If it is, maybe try making a feature to decrypt in chunks
Only happens on large update and DLC files from my knowledge (e.g. BOTW's DLC)
Also happens on BOTW's update

**Comment by TheSniperCatt0** [comment]
Yeah, this happened to me too on Linux using the appimage. Downgrading to 2.29 allowed me to decrypt.

**Comment by Xpl0itU** [comment]
Doesn't happen to me on v2.55 anymore
