### ISSUE TITLE
name adjustments of content!

### ISSUE THREAD

**Issue by darkuser89** [Xpl0itU/WiiUDownloader#99]
show content what they are! 

This is what it looks like for me at the moment
The Legend of Zelda Breath of the Wild [Game] [00050000101c9500]

I think it would be better if you still had options for

The Legend of Zelda Breath of the Wild [Game] [00050000101c9500] [Encrypted]
The Legend of Zelda Breath of the Wild [Game] [00050000101c9500] [Decrypted]
or
The Legend of Zelda Breath of the Wild [Game] [EU] [00050000101c9500]
The Legend of Zelda Breath of the Wild [EU] [Game] [00050000101c9500]

A good improvement would also be to copy the decrypted content directly into a new folder with the appropriate name.

The Legend of Zelda Breath of the Wild [Game] [00050000101c9500] [Decrypted]

**Comment by Xpl0itU** [comment]
Just go into the folder
